export const ADDINGREDIENT = 'ADDINGREDIENT'
export const REMOVEINGREDIENT = 'REMOVEADDINGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED'